name: Story Issue Check

on:
  issues:
    types:
      - opened

jobs:
  delete-story-issue-from-non-admin:
    if: contains(github.event.issue.labels.*.name, 'story') && github.event.issue.user.login != 'Madeline-Ellingson'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    env:
      NUMBER: ${{ github.event.issue.number }}
      BODY: "This issue was automatically deleted because it was submitted by a non-admin user. Please use the Bug Report or Feature Request template instead."
    steps:
      - uses: actions/checkout@v2
      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ github.token }}"
      - name: Add comment
        run: gh issue comment "$NUMBER" --body "$BODY"
      - name: Close issue
        run: gh issue close "$NUMBER"